version: '3'
services:
  testenv:
    image: us-docker.pkg.dev/vpc-host-nonprod-345521/np-docker/testenv:latest
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    volumes:
      # map your github credentials file and the app-config-credentials file
      - ${PWD}/app-config-locations.local.yaml:/app/configs/locations.yaml
